const paymentIntent = {
    id: 'pi_3Qhb8mH1BJzsAGIZ1tM1O3sw',
    object: 'payment_intent',
    amount: 18700,
    amount_capturable: 0,
    amount_details: { tip: {} },
    amount_received: 18700,
    application: null,
    application_fee_amount: null,
    automatic_payment_methods: null,
    canceled_at: null,
    cancellation_reason: null,
    capture_method: 'automatic_async',
    client_secret: 'pi_3Qhb8mH1BJzsAGIZ1tM1O3sw_secret_PjgSkJgPkA6gQXl39ggmiBX9h',
    confirmation_method: 'automatic',
    created: 1736964992,
    currency: 'usd',
    customer: null,
    description: null,
    invoice: null,
    last_payment_error: null,
    latest_charge: 'ch_3Qhb8mH1BJzsAGIZ1yZHHJwV',
    livemode: false,
    metadata: {},
    next_action: null,
    on_behalf_of: null,
    payment_method: 'pm_1Qhb8lH1BJzsAGIZSLdopjPp',
    payment_method_configuration_details: null,
    payment_method_options: {
      card: {
        installments: null,
        mandate_options: null,
        network: null,
        request_three_d_secure: 'automatic'
      }
    },
    payment_method_types: [ 'card' ],
    processing: null,
    receipt_email: null,
    review: null,
    setup_future_usage: null,
    shipping: null,
    source: null,
    statement_descriptor: null,
    statement_descriptor_suffix: null,
    status: 'succeeded',
    transfer_data: null,
    transfer_group: null
}