import React from 'react'

const PostView = () => {
  return (
    <div>Post</div>
  )
}

export default PostView; 

//ESTA VISTA TENDRA TRES BOTONES: 1 'PUBLICAR' DONDE SE ENVIARAN LOS POST (/LOSTANDFOUND), OTRO BOTON 'EDITAR' PARA MODIFICAR LA PUBLICACION (/EDIT/PAGE.TSX) Y OTRO BOTON QUE DICA 
// 'SALIR' SI NO VA A PUBLICAR O EDITAR SU PUBLICACION.