services:
  - name: back
    type: web
    env: node
    buildCommand: npm install        # Comando para instalar dependencias
    startCommand: npm run start:prod # Comando para iniciar la aplicación en producción
    envVars:
      - key: NODE_ENV
        value: production           # Aseguramos que el entorno sea de producción
    directory: /opt/render/project/back              # Correcto: indica que el 'package.json' está en la carpeta 'back'
    staticPublishPath: /dist         # Si tienes archivos estáticos en /dist (opcional)
